name: bindings typescript

on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  test:
    name: test generated libraries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest-16-cores, macos-13, windows-latest-8-cores]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          brew install colima
          colima start
      - name: Install wsl
        if: runner.os ==  'windows'
        uses: vedantmgoyal9/setup-wsl2@main
      - run: apt update && apt upgrade -y
        if: runner.os ==  'windows'
        shell: wsl-run {0} # add this to run the commands inside linux
      - run: ls -la
        if: runner.os ==  'windows'
        shell: wsl-run {0}
      - run: ls -la
        shell: bash
      - name: Run quickstart
        run: |
          docker run -d --name quickstart -p 8000:8000 -e ENABLE_LOGS=true -e NETWORK=local -e ENABLE_SOROBAN_RPC=true stellar/quickstart:testing
        shell: wsl-run {0}
      - run: |
          until [ "`docker inspect -f {{.State.Health.Status}} quickstart`"=="healthy" ]; do
              sleep 0.1;
          done;
        shell: bash
      - run: rustup update
      - run: cargo build
      - run: rustup target add wasm32-unknown-unknown
      - run: make build-test-wasms
      - run: npm ci && npm run test
        working-directory: cmd/crates/soroban-spec-typescript/ts-tests
      - name: quickstart logs
        if: always()
        run: docker logs quickstart
